#!/bin/bash

BASEDIR=$(dirname "$0")
echo "$BASEDIR"

HELP=$'Supported commands:\ndat --help\ndat create project_name\ndat add-page\ndat remove-page\ndat add-datasource \ndat remove-datasorce\ndat reload-datasource'

CMD=$1
shift

case $CMD in
create)
	{
        python $BASEDIR/create_project_script.py "$@" &&
        echo "New project '$1' created"
	} ||
    {
        echo "Exception occurred"
    }
	;;
add-page)
    {
        python $BASEDIR/create_page_script.py "$@"
	} ||
    {
        echo "Exception occurred"
    }
    ;;
remove-page)
    {
        python $BASEDIR/remove_page_script.py "$@"
	} ||
    {
        echo "Exception occurred"
    }
    ;;
add-datasource)
    {
        python $BASEDIR/load_data_script.py "$@"
	} ||
    {
        echo "Exception occurred"
    }
    ;;
remove-datasource)
    {
        python $BASEDIR/load_data_script.py "$@"
	} ||
    {
        echo "Exception occurred"
    }
    ;;
reload-datasources)
    {
        python $BASEDIR/reload_data_script.py "$@"
	} ||
    {
        echo "Exception occurred"
    }
    ;;
--help)
	echo "$HELP"
	;;
*)
	echo "dat: '$1' is not a dat command. See 'dat --help'."
	;;
esac
