#!/bin/bash

BASEDIR=$(dirname "$0")
echo "$BASEDIR"

HELP=$'Supported commands:\ndat --help\ndat create project_name\ndat add-page\ndat remove-page\ndat add-datasource \ndat remove-datasorce\ndat reload-datasource'

python $BASEDIR/dat_script.py "$@"
